---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cv-rtsp-server-shared-volume-claim
  namespace: cv    
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
  - ReadWriteOnce
