---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cv-rtsp-server-shared-volume-claim
  namespace: cv    
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
  - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: cv-rtsp-server-with-fileupload
  name: cv-rtsp-server-with-fileupload
  namespace: cv
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cv-rtsp-server-with-fileupload
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cv-rtsp-server-with-fileupload
    spec:
      containers:
      - env:
        - name: FORCE_REPLACE_ID
          value: "0"
        - name: FILEUPLOADER_FOLDER_ROOT
          value: /data
        image: {{ .Values.image.rtspfileuploadercontainer }}
        imagePullPolicy: Always
        name: cv-rtsp-server-with-fileupload-fileupload
        ports:
        - containerPort: 8080
          name: upload
          protocol: TCP
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: cv-rtsp-server-shared-volume
      - image: busybox
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
          tcpSocket:
            port: 554
          timeoutSeconds: 1
        name: cv-rtsp-server-with-fileupload-live555
        ports:
        - containerPort: 554
          name: rtsp
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 554
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /live555/data
          name: cv-rtsp-server-shared-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      volumes:
      - name: cv-rtsp-server-shared-volume
        persistentVolumeClaim:
          claimName: cv-rtsp-server-shared-volume-claim
